set_property PACKAGE_PIN T12 [get_ports {gpio_led_tri_o[3]}]
set_property PACKAGE_PIN U12 [get_ports {gpio_led_tri_o[2]}]
set_property PACKAGE_PIN V12 [get_ports {gpio_led_tri_o[1]}]
set_property PACKAGE_PIN W13 [get_ports {gpio_led_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_tri_o[0]}]
